services:
  unibot:
    container_name: unibot
    user: "0:0"  # root
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    dns:
      - 10.136.201.114

    env_file:
      - .env

    environment:
      TZ: America/New_York
      HEALTH_PORT: 6969
      INSTANCE_TAG: vm

    ports:
      - "6969:6969"

    volumes:
      - /mnt/shared/unibot:/unibot

    ulimits:
      nofile:
        soft: 8192
        hard: 8192
